### ISSUE TITLE
Gak ada respon command

### ISSUE THREAD

**Issue by alvino-prog** [Rlxfly/re-md#49]
![image](https://user-images.githubusercontent.com/54900965/208269032-da1c1713-5991-4146-8d19-ed167a193979.png)

pas pakai cmd, ga ada respon sama sekali, error

**Comment by ImYanXiao** [comment]
> ![image](https://user-images.githubusercontent.com/54900965/208269032-da1c1713-5991-4146-8d19-ed167a193979.png)
> 
> pas pakai cmd, ga ada respon sama sekali, error

Baiklh, ownernya ga mw ngefix :v

**Comment by alvino-prog** [comment]
Omoshiroi

2022年12月20日(火) 14:04 Xiao Yan? ***@***.***>:

**Comment by Rlxfly** [comment]
mana ga ada

**Comment by Rlxfly** [comment]
update baileys ke versi latest ajh
